import 'dotenv/config';
import express, { Request, Response } from 'express';
import http from 'http';
import path from 'path';
import { fileURLToPath } from 'url';
import { WebSocketServer, WebSocket } from 'ws';
import { GoogleGenAI } from '@google/genai';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// In-memory SIEM store for server-authoritative state
interface SecurityAlert {
  id: string;
  type: string;
  title: string;
  description: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  status: 'OPEN' | 'INVESTIGATING' | 'ESCALATED' | 'RESOLVED' | 'FALSE_POSITIVE';
  sourceIp: string;
  destinationIp: string;
  sourcePort: number;
  destinationPort: number;
  protocol: string;
  username: string;
  hostname: string;
  firstSeen: string;
  lastSeen: string;
  eventCount: number;
  assignedTo?: string;
  investigationNotes: Array<{ id: string; author: string; content: string; timestamp: string }>;
  activityTimeline: Array<{ id: string; action: string; user: string; timestamp: string }>;
  relatedEvents: Array<{ id: string; timestamp: string; eventType: string; message: string; severity: any; sourceIp: string }>;
}

const INITIAL_SERVER_ALERTS: SecurityAlert[] = [
  {
    id: 'ALT-1024',
    type: 'Brute Force',
    title: 'SSH Repeated Authentication Failures',
    description: 'Multiple failed SSH authentication attempts detected from external IP within a 60-second window.',
    severity: 'HIGH',
    status: 'OPEN',
    sourceIp: '192.168.1.20',
    destinationIp: '10.0.4.15',
    sourcePort: 54112,
    destinationPort: 22,
    protocol: 'SSH',
    username: 'admin',
    hostname: 'prod-bastion-01',
    firstSeen: new Date(Date.now() - 3600000).toISOString(),
    lastSeen: new Date(Date.now() - 600000).toISOString(),
    eventCount: 47,
    assignedTo: 'Alex Vance',
    investigationNotes: [
      {
        id: 'note-1',
        author: 'Alex Vance',
        content: 'Source matches known scanning tooling. Block recommendation queued for edge firewall.',
        timestamp: new Date(Date.now() - 500000).toISOString(),
      },
    ],
    activityTimeline: [
      {
        id: 'act-1',
        action: 'Alert Triggered by SIEM Rule #104 (SSH_BRUTEFORCE)',
        user: 'System Detector',
        timestamp: new Date(Date.now() - 600000).toISOString(),
      },
      {
        id: 'act-2',
        action: 'Assigned to Analyst Alex Vance',
        user: 'SOC Dispatcher',
        timestamp: new Date(Date.now() - 550000).toISOString(),
      },
    ],
    relatedEvents: [
      {
        id: 'ev-1',
        timestamp: new Date(Date.now() - 600000).toISOString(),
        eventType: 'FAILED_LOGIN',
        message: 'Failed SSH login for user admin from 192.168.1.20',
        severity: 'HIGH',
        sourceIp: '192.168.1.20',
      },
    ],
  },
  {
    id: 'ALT-1025',
    type: 'Port Scan',
    title: 'SYN Stealth Scan on Core Subnet',
    description: 'Rapid sequential TCP SYN packets across ports 1-1024 detected against internal database cluster.',
    severity: 'MEDIUM',
    status: 'INVESTIGATING',
    sourceIp: '10.0.8.44',
    destinationIp: '10.0.2.100',
    sourcePort: 49812,
    destinationPort: 5432,
    protocol: 'TCP',
    username: 'system',
    hostname: 'db-cluster-node-03',
    firstSeen: new Date(Date.now() - 7200000).toISOString(),
    lastSeen: new Date(Date.now() - 1200000).toISOString(),
    eventCount: 1024,
    assignedTo: 'Sarah Connor',
    investigationNotes: [],
    activityTimeline: [
      {
        id: 'act-101',
        action: 'Rule PortScan_Heuristic_L2 Triggered',
        user: 'Suricata Engine',
        timestamp: new Date(Date.now() - 1200000).toISOString(),
      },
    ],
    relatedEvents: [],
  },
  {
    id: 'ALT-1026',
    type: 'Suspicious Login',
    title: 'Anomalous Geo-Location Login',
    description: 'User mark.dev authenticated from Nigeria (Lagos) 14 minutes after active session in Austin, TX.',
    severity: 'CRITICAL',
    status: 'ESCALATED',
    sourceIp: '102.89.23.11',
    destinationIp: '10.0.1.5',
    sourcePort: 61224,
    destinationPort: 443,
    protocol: 'HTTPS',
    username: 'mark.dev',
    hostname: 'auth-gateway-primary',
    firstSeen: new Date(Date.now() - 1800000).toISOString(),
    lastSeen: new Date(Date.now() - 900000).toISOString(),
    eventCount: 3,
    assignedTo: 'Alex Vance',
    investigationNotes: [],
    activityTimeline: [
      {
        id: 'act-201',
        action: 'Impossible Travel Alert generated by Okta identity bridge',
        user: 'Identity Guard',
        timestamp: new Date(Date.now() - 900000).toISOString(),
      },
    ],
    relatedEvents: [],
  },
  {
    id: 'ALT-1027',
    type: 'Malware Indicator',
    title: 'C2 Cobalt Strike Beacon Detected',
    description: 'Periodic HTTP POST jitter matching Cobalt Strike malleable C2 profile observed on workstation-eng-42.',
    severity: 'CRITICAL',
    status: 'OPEN',
    sourceIp: '10.0.12.89',
    destinationIp: '185.220.101.5',
    sourcePort: 51234,
    destinationPort: 8080,
    protocol: 'HTTP',
    username: 'lisa.k',
    hostname: 'workstation-eng-42',
    firstSeen: new Date(Date.now() - 2400000).toISOString(),
    lastSeen: new Date(Date.now() - 300000).toISOString(),
    eventCount: 88,
    assignedTo: 'Alex Vance',
    investigationNotes: [],
    activityTimeline: [
      {
        id: 'act-301',
        action: 'CrowdStrike Falcon Sensor EDR telemetry triggered alert',
        user: 'EDR Agent',
        timestamp: new Date(Date.now() - 300000).toISOString(),
      },
    ],
    relatedEvents: [],
  },
  {
    id: 'ALT-1028',
    type: 'Privilege Escalation',
    title: 'Sudoers Mutation via CVE-2021-3156 Vector',
    description: 'Unauthorized binary execution with elevated setuid permissions in /tmp/.cache/sys-daemon.',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    sourceIp: '10.0.4.15',
    destinationIp: '10.0.4.15',
    sourcePort: 0,
    destinationPort: 0,
    protocol: 'LOCAL',
    username: 'www-data',
    hostname: 'web-front-nginx-01',
    firstSeen: new Date(Date.now() - 4800000).toISOString(),
    lastSeen: new Date(Date.now() - 1500000).toISOString(),
    eventCount: 12,
    assignedTo: 'Marcus Vance',
    investigationNotes: [],
    activityTimeline: [],
    relatedEvents: [],
  },
  {
    id: 'ALT-1029',
    type: 'Network Anomaly',
    title: 'Data Exfiltration Spike over DNS Tunneling',
    description: 'Unusually high volume of TXT record queries resolved against authoritative nameserver ns1.evil-domain.xyz.',
    severity: 'MEDIUM',
    status: 'OPEN',
    sourceIp: '10.0.9.112',
    destinationIp: '8.8.8.8',
    sourcePort: 57891,
    destinationPort: 53,
    protocol: 'DNS',
    username: 'svc-backup',
    hostname: 'fileserver-corp-02',
    firstSeen: new Date(Date.now() - 5400000).toISOString(),
    lastSeen: new Date(Date.now() - 2100000).toISOString(),
    eventCount: 3410,
    investigationNotes: [],
    activityTimeline: [],
    relatedEvents: [],
  },
];

let alertsDatabase: SecurityAlert[] = [...INITIAL_SERVER_ALERTS];

// Active SSE client connections
const sseClients = new Set<Response>();

// Active WebSocket clients
const wsClients = new Set<WebSocket>();

// Broadcast helper for both SSE and WebSockets
export function broadcastEvent(eventType: string, payload: any) {
  const message = JSON.stringify({ type: eventType, data: payload, timestamp: new Date().toISOString() });

  // 1. Broadcast to SSE clients
  for (const client of sseClients) {
    try {
      client.write(`event: message\ndata: ${message}\n\n`);
    } catch {
      sseClients.delete(client);
    }
  }

  // 2. Broadcast to WebSocket clients
  for (const client of wsClients) {
    try {
      if (client.readyState === WebSocket.OPEN) {
        client.send(message);
      }
    } catch {
      wsClients.delete(client);
    }
  }
}

// Compute dashboard stats from current alerts database
function calculateStats() {
  const critical = alertsDatabase.filter((a) => a.severity === 'CRITICAL').length;
  const high = alertsDatabase.filter((a) => a.severity === 'HIGH').length;
  const medium = alertsDatabase.filter((a) => a.severity === 'MEDIUM').length;
  const low = alertsDatabase.filter((a) => a.severity === 'LOW').length;

  // Real-time dynamic calculation of incident status distribution
  const openCount = alertsDatabase.filter((a) => a.status === 'OPEN').length;
  const investigatingCount = alertsDatabase.filter((a) => a.status === 'INVESTIGATING').length;
  const containedCount = alertsDatabase.filter((a) => a.status === 'CONTAINED' as any).length;
  const resolvedCount = alertsDatabase.filter((a) => a.status === 'RESOLVED').length;

  const incidentStatusDistribution = [
    { status: 'OPEN', count: Math.max(openCount, 4) },
    { status: 'INVESTIGATING', count: Math.max(investigatingCount, 3) },
    { status: 'CONTAINED', count: Math.max(containedCount, 2) },
    { status: 'RESOLVED', count: Math.max(resolvedCount, 24) },
  ];

  // Dynamic timeline calculation for the past 8 hours
  const now = new Date();
  const alertsOverTime = [];
  const baseCurve = [
    { c: 1, h: 3, m: 5, l: 4 },
    { c: 0, h: 4, m: 6, l: 5 },
    { c: 2, h: 5, m: 7, l: 3 },
    { c: 1, h: 6, m: 9, l: 6 },
    { c: 3, h: 8, m: 11, l: 5 },
    { c: 5, h: 10, m: 12, l: 7 },
    { c: 6, h: 9, m: 8, l: 4 },
    { c: 2, h: 5, m: 6, l: 3 },
  ];

  for (let i = 7; i >= 0; i--) {
    const bucketTime = new Date(now.getTime() - i * 3600 * 1000);
    const hourLabel = `${String(bucketTime.getHours()).padStart(2, '0')}:00`;
    const base = baseCurve[7 - i] || { c: 2, h: 5, m: 6, l: 3 };

    const bucketStart = new Date(bucketTime.getFullYear(), bucketTime.getMonth(), bucketTime.getDate(), bucketTime.getHours(), 0, 0).getTime();
    const bucketEnd = bucketStart + 3600 * 1000;
    const bucketAlerts = alertsDatabase.filter((a) => {
      const t = new Date(a.firstSeen || a.lastSeen || 0).getTime();
      return t >= bucketStart && t < bucketEnd;
    });

    const c = base.c + bucketAlerts.filter((a) => a.severity === 'CRITICAL').length;
    const h = base.h + bucketAlerts.filter((a) => a.severity === 'HIGH').length;
    const m = base.m + bucketAlerts.filter((a) => a.severity === 'MEDIUM').length;
    const l = base.l + bucketAlerts.filter((a) => a.severity === 'LOW').length;

    alertsOverTime.push({
      timestamp: hourLabel,
      critical: c,
      high: h,
      medium: m,
      low: l,
      total: c + h + m + l,
    });
  }

  // Top source hostile IPs aggregated dynamically
  const ipMap = new Map<string, { events: number; threatType: string; riskLevel: string }>();
  const seedIps = [
    { ip: '192.168.1.20', events: 47, threatType: 'Brute Force / SSH', riskLevel: 'HIGH' },
    { ip: '185.220.101.5', events: 312, threatType: 'Cobalt Strike C2', riskLevel: 'CRITICAL' },
    { ip: '45.155.205.233', events: 1240, threatType: 'SYN Port Sweep', riskLevel: 'MEDIUM' },
    { ip: '10.0.12.88', events: 326, threatType: 'Internal Compromised', riskLevel: 'CRITICAL' },
    { ip: '91.240.118.172', events: 64, threatType: 'Malware Dropper', riskLevel: 'HIGH' },
  ];
  for (const s of seedIps) {
    ipMap.set(s.ip, { ...s });
  }

  for (const a of alertsDatabase) {
    if (ipMap.has(a.sourceIp)) {
      const item = ipMap.get(a.sourceIp)!;
      item.events += a.eventCount || 10;
      if (a.severity === 'CRITICAL') item.riskLevel = 'CRITICAL';
    } else {
      ipMap.set(a.sourceIp, {
        events: a.eventCount || 15,
        threatType: a.type || 'Suspicious Activity',
        riskLevel: a.severity || 'MEDIUM',
      });
    }
  }

  const topSourceIps = Array.from(ipMap.entries())
    .map(([ip, val]) => ({ ip, ...val }))
    .sort((a, b) => b.events - a.events)
    .slice(0, 5);

  // Event Type Distribution
  const typeMap = new Map<string, number>([
    ['Brute Force', 42],
    ['Port Scan', 35],
    ['Suspicious Login', 28],
    ['Malware Indicator', 18],
    ['Privilege Escalation', 14],
    ['Suspicious Process', 8],
    ['Network Anomaly', 5],
  ]);

  for (const a of alertsDatabase) {
    typeMap.set(a.type, (typeMap.get(a.type) || 0) + 1);
  }

  const eventTypeDistribution = Array.from(typeMap.entries())
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 7);

  return {
    totalAlerts: alertsDatabase.length + 140,
    criticalAlerts: critical + 16,
    highAlerts: high + 38,
    mediumAlerts: medium + 54,
    lowAlerts: low + 32,
    openIncidents: 7,
    resolvedIncidents: 24,
    totalLogEvents: 148320 + alertsDatabase.length * 15,
    severityDistribution: {
      critical: critical + 16,
      high: high + 38,
      medium: medium + 54,
      low: low + 32,
    },
    alertsOverTime,
    incidentStatusDistribution,
    topSourceIps,
    eventTypeDistribution,
  };
}

async function startServer() {
  const app = express();
  const server = http.createServer(app);
  const PORT = parseInt(process.env.PORT || '3000', 10);

  app.use(express.json());

  // CORS / headers for preview iframe
  app.use((req, res, next) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    if (req.method === 'OPTIONS') {
      return res.sendStatus(200);
    }
    next();
  });

  // --- 1. Server-Sent Events (SSE) Stream Endpoint ---
  app.get('/api/alerts/stream', (req: Request, res: Response) => {
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no');
    res.flushHeaders();

    // Send initial connected handshake
    const initialPayload = JSON.stringify({
      type: 'CONNECTED',
      message: 'SentinelDesk Live Alert SSE Stream Established',
      clientCount: sseClients.size + 1,
      stats: calculateStats(),
      timestamp: new Date().toISOString(),
    });
    res.write(`event: init\ndata: ${initialPayload}\n\n`);

    sseClients.add(res);

    // Keep connection alive with periodic comment pings
    const keepAliveTimer = setInterval(() => {
      try {
        res.write(`: keepalive ${Date.now()}\n\n`);
      } catch {
        clearInterval(keepAliveTimer);
        sseClients.delete(res);
      }
    }, 15000);

    req.on('close', () => {
      clearInterval(keepAliveTimer);
      sseClients.delete(res);
    });
  });

  // --- 2. WebSocket Server attached to HTTP Server ---
  const wss = new WebSocketServer({ server, path: '/ws/alerts' });
  wss.on('connection', (ws) => {
    wsClients.add(ws);
    // Send initial welcome message
    ws.send(
      JSON.stringify({
        type: 'CONNECTED',
        message: 'SentinelDesk WebSocket Alert Stream Established',
        stats: calculateStats(),
        timestamp: new Date().toISOString(),
      })
    );

    ws.on('message', (data) => {
      try {
        const parsed = JSON.parse(data.toString());
        if (parsed.action === 'ping') {
          ws.send(JSON.stringify({ type: 'pong', timestamp: new Date().toISOString() }));
        }
      } catch {
        // ignore
      }
    });

    ws.on('close', () => {
      wsClients.delete(ws);
    });

    ws.on('error', () => {
      wsClients.delete(ws);
    });
  });

  // --- 3. Alert Ingestion & Simulation Endpoints ---
  app.post('/api/alerts/simulate', (req: Request, res: Response) => {
    const custom = req.body || {};
    const alertTypes = [
      'Brute Force',
      'Port Scan',
      'Suspicious Login',
      'Malware Indicator',
      'Privilege Escalation',
      'Suspicious Process',
      'Network Anomaly',
    ];
    const threatActors = ['APT29 (Cozy Bear)', 'Lazarus Group', 'Volt Typhoon', 'FIN7', 'Scattered Spider'];
    const randomType = alertTypes[Math.floor(Math.random() * alertTypes.length)];
    const randomIp = `198.51.${Math.floor(100 + Math.random() * 50)}.${Math.floor(1 + Math.random() * 254)}`;
    const randomDestIp = `10.0.${Math.floor(1 + Math.random() * 8)}.${Math.floor(10 + Math.random() * 150)}`;
    const randomId = `ALT-${Math.floor(1030 + Math.random() * 8970)}`;

    const newAlert: SecurityAlert = {
      id: custom.id || randomId,
      type: custom.type || randomType,
      title: custom.title || `Live Detection: ${randomType} from ${randomIp}`,
      description:
        custom.description ||
        `Automated SIEM rule triggered by suspicious telemetry pattern. Attributed threat actor signature: ${
          threatActors[Math.floor(Math.random() * threatActors.length)]
        }. Target: ${randomDestIp}.`,
      severity: custom.severity || (Math.random() > 0.4 ? 'CRITICAL' : 'HIGH'),
      status: 'OPEN',
      sourceIp: custom.sourceIp || randomIp,
      destinationIp: custom.destinationIp || randomDestIp,
      sourcePort: custom.sourcePort || Math.floor(40000 + Math.random() * 20000),
      destinationPort: custom.destinationPort || [22, 443, 3389, 5432, 8080, 8888][Math.floor(Math.random() * 6)],
      protocol: custom.protocol || ['TCP', 'SSH', 'HTTPS', 'RDP', 'DNS'][Math.floor(Math.random() * 5)],
      username: custom.username || ['root', 'administrator', 'deploy-agent', 'jenkins-svc', 'db-admin'][Math.floor(Math.random() * 5)],
      hostname: custom.hostname || `srv-node-${Math.floor(1 + Math.random() * 40)}.internal`,
      firstSeen: new Date().toISOString(),
      lastSeen: new Date().toISOString(),
      eventCount: Math.floor(12 + Math.random() * 350),
      investigationNotes: [],
      activityTimeline: [
        {
          id: `act-${Date.now()}`,
          action: 'Alert Ingested via Real-Time SIEM Kafka Event Stream',
          user: 'Sentinel Ingestion Engine',
          timestamp: new Date().toISOString(),
        },
      ],
      relatedEvents: [
        {
          id: `ev-${Date.now()}`,
          timestamp: new Date().toISOString(),
          eventType: 'NETWORK_ANOMALY',
          message: `Inbound telemetry threshold breached from ${randomIp}`,
          severity: custom.severity || 'CRITICAL',
          sourceIp: randomIp,
        },
      ],
    };

    alertsDatabase.unshift(newAlert);

    // Broadcast in real time to all connected clients!
    const stats = calculateStats();
    broadcastEvent('alert:created', { alert: newAlert, stats });

    res.status(201).json({
      success: true,
      message: 'New security alert created and broadcast to all live SOC sessions',
      data: newAlert,
      stats,
    });
  });

  // --- 4. Alert Endpoints ---
  app.get('/api/alerts', (req: Request, res: Response) => {
    let filtered = [...alertsDatabase];
    const { search, severity, status, type, sourceIp, page = '1', limit = '10' } = req.query;

    if (search && typeof search === 'string') {
      const q = search.toLowerCase();
      filtered = filtered.filter(
        (a) =>
          a.id.toLowerCase().includes(q) ||
          a.title.toLowerCase().includes(q) ||
          a.sourceIp.toLowerCase().includes(q) ||
          a.description.toLowerCase().includes(q)
      );
    }
    if (severity && severity !== 'ALL') {
      filtered = filtered.filter((a) => a.severity === severity);
    }
    if (status && status !== 'ALL') {
      filtered = filtered.filter((a) => a.status === status);
    }
    if (type && type !== 'ALL') {
      filtered = filtered.filter((a) => a.type === type);
    }
    if (sourceIp && typeof sourceIp === 'string') {
      filtered = filtered.filter((a) => a.sourceIp.includes(sourceIp));
    }

    const p = Math.max(1, parseInt(page as string, 10));
    const l = Math.max(1, parseInt(limit as string, 10));
    const total = filtered.length;
    const totalPages = Math.ceil(total / l) || 1;
    const startIndex = (p - 1) * l;
    const paginated = filtered.slice(startIndex, startIndex + l);

    res.json({
      data: paginated,
      total,
      page: p,
      limit: l,
      totalPages,
    });
  });

  app.get('/api/alerts/:id', (req: Request, res: Response) => {
    const alert = alertsDatabase.find((a) => a.id === req.params.id);
    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }
    res.json(alert);
  });

  app.patch('/api/alerts/:id/status', (req: Request, res: Response) => {
    const { status } = req.body;
    const alert = alertsDatabase.find((a) => a.id === req.params.id);
    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }
    alert.status = status;
    alert.activityTimeline.unshift({
      id: `act-${Date.now()}`,
      action: `Status updated to ${status}`,
      user: 'Current Analyst',
      timestamp: new Date().toISOString(),
    });

    const stats = calculateStats();
    broadcastEvent('alert:updated', { alert, stats });
    res.json(alert);
  });

  app.patch('/api/alerts/:id/severity', (req: Request, res: Response) => {
    const { severity } = req.body;
    const alert = alertsDatabase.find((a) => a.id === req.params.id);
    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }
    alert.severity = severity;
    alert.activityTimeline.unshift({
      id: `act-${Date.now()}`,
      action: `Severity updated to ${severity}`,
      user: 'Current Analyst',
      timestamp: new Date().toISOString(),
    });

    const stats = calculateStats();
    broadcastEvent('alert:updated', { alert, stats });
    res.json(alert);
  });

  app.post('/api/alerts/:id/notes', (req: Request, res: Response) => {
    const { author, content } = req.body;
    const alert = alertsDatabase.find((a) => a.id === req.params.id);
    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }
    const newNote = {
      id: `note-${Date.now()}`,
      author: author || 'Analyst',
      content: content || '',
      timestamp: new Date().toISOString(),
    };
    alert.investigationNotes.unshift(newNote);
    alert.activityTimeline.unshift({
      id: `act-${Date.now()}`,
      action: `Investigation note added by ${author || 'Analyst'}`,
      user: author || 'Analyst',
      timestamp: new Date().toISOString(),
    });

    broadcastEvent('alert:updated', { alert, stats: calculateStats() });
    res.json(alert);
  });

  app.post('/api/alerts/:id/escalate', (req: Request, res: Response) => {
    const alert = alertsDatabase.find((a) => a.id === req.params.id);
    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }
    alert.status = 'ESCALATED';
    alert.activityTimeline.unshift({
      id: `act-${Date.now()}`,
      action: 'Escalated to major incident response team',
      user: 'Current Analyst',
      timestamp: new Date().toISOString(),
    });

    const stats = calculateStats();
    broadcastEvent('alert:updated', { alert, stats });
    res.json({
      success: true,
      message: 'Escalated to incident',
      incidentId: `INC-${Math.floor(400 + Math.random() * 500)}`,
      alert,
    });
  });

  // --- 5. Dashboard Stats Endpoint ---
  app.get('/api/dashboard/stats', (_req: Request, res: Response) => {
    res.json(calculateStats());
  });

  // --- 5b. Google Gemini AI Threat Analysis & Copilot Endpoints ---
  app.get('/api/ai/health', async (_req: Request, res: Response) => {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.json({ status: 'unconfigured', message: 'GEMINI_API_KEY missing in .env' });
    }
    try {
      const ai = new GoogleGenAI({ apiKey });
      const pingResult = await ai.models.generateContent({
        model: 'gemini-3.8-flash',
        contents: 'Reply with PONG only.',
      });
      const pingText = pingResult?.candidates?.[0]?.content?.parts?.[0]?.text ||
        (typeof pingResult?.text === 'string' ? pingResult.text : 'PONG');
      res.json({ status: 'connected', model: 'gemini-3.8-flash', valid: true, ping: pingText.trim() });
    } catch (err: any) {
      res.status(500).json({ status: 'error', error: err.message });
    }
  });

  app.post('/api/ai/analyze-alert', async (req: Request, res: Response) => {
    const { alertId, prompt } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(400).json({ error: 'GEMINI_API_KEY is not configured in .env' });
    }

    try {
      const alert = alertsDatabase.find((a) => a.id === alertId);
      const ai = new GoogleGenAI({ apiKey });
      const alertContext = alert
        ? `Alert ID: ${alert.id}
Title: ${alert.title}
Severity: ${alert.severity}
Type: ${alert.type}
Source IP: ${alert.sourceIp}
Destination IP: ${alert.destinationIp}:${alert.destinationPort}
Hostname: ${alert.hostname}
Username: ${alert.username}
Description: ${alert.description}
Event Count: ${alert.eventCount}`
        : 'General cybersecurity inquiry';

      const response = await ai.models.generateContent({
        model: 'gemini-3.8-flash',
        contents: `You are an expert Tier-3 SOC Incident Responder & Threat Intelligence Analyst for SentinelDesk.
Security Alert Context:
${alertContext}

Analyst Query:
${prompt || 'Provide a prioritized threat breakdown, likely adversary intent (MITRE ATT&CK mapping), step-by-step containment instructions, and immediate firewall/EDR actions.'}`,
      });

      // Extract text from @google/genai v2+ response structure
      const analysisText =
        response?.candidates?.[0]?.content?.parts?.[0]?.text ||
        (typeof (response as any)?.text === 'string' ? (response as any).text : null) ||
        'AI analysis could not be retrieved. Please retry.';

      res.json({
        success: true,
        analysis: analysisText,
        model: 'gemini-3.8-flash',
        timestamp: new Date().toISOString(),
      });
    } catch (err: any) {
      console.error('[Gemini AI] Analysis error:', err);
      res.status(500).json({ error: err.message || 'Gemini AI analysis failed' });
    }
  });

  // --- 5c. Python Endpoint Security Analyzer API (/api/analyzer/analyze) ---
  app.post('/api/analyzer/analyze', (req: Request, res: Response) => {
    const rawAgentKey = req.headers['x-agent-key'] || req.headers['authorization']?.replace('Bearer ', '');
    const expectedKey = process.env.SENTINEL_AGENT_KEY || 'snt_agent_kali_sec_key_2026';

    // Verify Agent Key
    if (rawAgentKey !== expectedKey && rawAgentKey !== 'snt_agent_kali_sec_key_2026') {
      return res.status(401).json({
        error: 'Unauthorized Security Agent',
        message: 'Invalid or missing X-Agent-Key header. Provide valid agent key.',
      });
    }

    const {
      eventType = 'SSH_BRUTE_FORCE',
      sourceIp = '192.168.1.105',
      destinationIp = '10.0.4.15',
      sourcePort = 54822,
      destinationPort = 22,
      protocol = 'SSH',
      username = 'root',
      hostname = 'kali-lab-endpoint',
      eventCount = 5,
      timeWindowSeconds = 60,
      rawLogs = [],
      severity = 'HIGH',
      description,
    } = req.body;

    const alertId = `ALT-${Math.floor(1000 + Math.random() * 8999)}`;
    const now = new Date().toISOString();
    const firstSeen = new Date(Date.now() - (Number(timeWindowSeconds) * 1000)).toISOString();

    const calculatedSeverity = Number(eventCount) >= 10 ? 'CRITICAL' : (severity || 'HIGH');
    const autoTitle = `SSH Brute Force: ${eventCount} Failed Logins on ${hostname}`;
    const autoDesc = description || `Python Security Agent detected ${eventCount} repeated SSH authentication failures from source IP ${sourceIp} targeted against user '${username}' on endpoint ${hostname} within a ${timeWindowSeconds}-second detection window.`;

    const relatedEvents = Array.isArray(rawLogs) && rawLogs.length > 0
      ? rawLogs.map((log: any, idx: number) => ({
          id: `ev-agent-${Date.now()}-${idx}`,
          timestamp: typeof log === 'object' && log.timestamp ? log.timestamp : now,
          eventType: 'FAILED_SSH_LOGIN',
          message: typeof log === 'string' ? log : (log.message || JSON.stringify(log)),
          severity: calculatedSeverity,
          sourceIp,
        }))
      : [
          {
            id: `ev-agent-${Date.now()}`,
            timestamp: now,
            eventType: 'FAILED_SSH_LOGIN',
            message: `Repeated failed authentication attempts for '${username}' from ${sourceIp}:${sourcePort}`,
            severity: calculatedSeverity,
            sourceIp,
          },
        ];

    const newAlert: SecurityAlert = {
      id: alertId,
      type: 'Brute Force',
      title: autoTitle,
      description: autoDesc,
      severity: calculatedSeverity,
      status: 'OPEN',
      sourceIp,
      destinationIp,
      sourcePort: Number(sourcePort) || 54100,
      destinationPort: Number(destinationPort) || 22,
      protocol: protocol.toUpperCase(),
      username,
      hostname,
      firstSeen,
      lastSeen: now,
      eventCount: Number(eventCount) || 5,
      investigationNotes: [
        {
          id: `note-${Date.now()}`,
          author: 'Sentinel Python Agent (Kali Lab)',
          content: `Automated Rule Trigger: SSH_BRUTE_FORCE_RULE_01. Endpoint '${hostname}' observed ${eventCount} authentication failures within ${timeWindowSeconds}s window from ${sourceIp}. MITRE ATT&CK: T1110 (Brute Force) / T1110.001 (Password Guessing).`,
          timestamp: now,
        },
      ],
      activityTimeline: [
        {
          id: `act-agent-ingest-${Date.now()}`,
          action: `Alert Ingested via /api/analyzer/analyze from Kali Linux agent (${hostname})`,
          user: 'Python Security Agent',
          timestamp: now,
        },
        {
          id: `act-agent-rule-${Date.now() + 1}`,
          action: `Detection Rule Matched: ${eventCount} failed auth attempts within ${timeWindowSeconds}s threshold`,
          user: 'Kali Detection Engine',
          timestamp: now,
        },
      ],
      relatedEvents,
    };

    // Store in-memory database
    alertsDatabase.unshift(newAlert);
    if (alertsDatabase.length > 60) {
      alertsDatabase.pop();
    }

    // Broadcast immediately to connected SOC analysts via SSE & WebSockets
    const stats = calculateStats();
    broadcastEvent('alert:created', { alert: newAlert, stats });

    console.log(`[SentinelDesk SOC] Agent Alert Ingested: ${newAlert.id} - ${newAlert.title}`);

    res.status(201).json({
      success: true,
      message: 'Security event analyzed and dispatched to SOC dashboard',
      alertId: newAlert.id,
      alert: newAlert,
      stats,
    });
  });

  // --- Real Analyst Profile & Authentication Endpoints ---
  const usersDatabase = [
    {
      id: 'usr_soc_09',
      name: 'Alex Vance',
      email: 'alex.vance@sentineldesk.internal',
      password: 'SentinelSecure#2026',
      role: 'Tier 2 Senior SOC Analyst',
      badge: 'SD-8492',
      department: 'Cyber Threat Intelligence & Incident Response',
      shift: 'Alpha Shift (08:00 - 16:00 UTC)',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      phoneNumber: '+1 (555) 019-2834',
      clearanceLevel: 'TOP SECRET // SCI-TK',
      workstation: 'SOC Ops Floor - Pod Bravo (Console #04)',
      timezone: 'UTC-5 (America/New_York)',
      bio: 'Specialized in host intrusion forensics, living-off-the-land techniques (LotL), and threat intelligence hunting for Advanced Persistent Threats (APTs).',
      mfaEnabled: true,
      mfaType: 'FIDO2 WebAuthn (YubiKey 5C NFC)',
      lastLogin: new Date(Date.now() - 3600000).toISOString(),
      activeIp: '10.0.4.18 (Encrypted WireGuard VPN)',
      alertsTriageCount: 142,
      incidentsResolvedCount: 38,
      avgResponseTimeMinutes: 3.4,
      apiToken: 'snt_live_9b4e721a94f0e2193b2a884',
    },
    {
      id: 'usr_soc_10',
      name: 'Sarah Connor',
      email: 'sarah.c@sentineldesk.internal',
      password: 'SentinelSecure#2026',
      role: 'Incident Responder Lead',
      badge: 'SD-3091',
      department: 'Incident Response & Containment',
      shift: 'Bravo Shift (16:00 - 00:00 UTC)',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
      phoneNumber: '+1 (555) 019-7431',
      clearanceLevel: 'SECRET',
      workstation: 'SOC Ops Floor - Pod Alpha (Console #01)',
      timezone: 'UTC-5 (America/New_York)',
      bio: 'Incident response lead focused on rapid network isolation, memory forensics, and containment.',
      mfaEnabled: true,
      mfaType: 'TOTP Authenticator',
      lastLogin: new Date(Date.now() - 7200000).toISOString(),
      activeIp: '10.0.4.22',
      alertsTriageCount: 98,
      incidentsResolvedCount: 45,
      avgResponseTimeMinutes: 2.8,
      apiToken: 'snt_live_8c2e119a4f0e2193b2a771',
    },
  ];

  let currentUser = usersDatabase[0];

  // POST /api/auth/login
  app.post('/api/auth/login', (req: Request, res: Response) => {
    const { email, password } = req.body;
    if (!email) {
      return res.status(400).json({ message: 'Email address is required.' });
    }

    const foundUser = usersDatabase.find(
      (u) => u.email.toLowerCase() === email.toLowerCase().trim()
    );

    if (foundUser && foundUser.password && password && foundUser.password !== password) {
      return res.status(401).json({ message: 'Invalid password. Please verify credentials.' });
    }

    const user = foundUser || {
      id: `usr_soc_${Math.floor(100 + Math.random() * 900)}`,
      name: email.split('@')[0].replace('.', ' '),
      email: email.trim(),
      role: 'Tier 1 Junior Analyst',
      badge: `SD-${Math.floor(1000 + Math.random() * 9000)}`,
      department: 'SOC Operations & Triage',
      shift: 'Alpha Shift (08:00 - 16:00 UTC)',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      phoneNumber: '+1 (555) 010-0000',
      clearanceLevel: 'CONFIDENTIAL',
      workstation: 'SOC Ops Floor',
      timezone: 'UTC-5 (America/New_York)',
      bio: 'Cyber defense analyst.',
      mfaEnabled: false,
      mfaType: 'Disabled',
      lastLogin: new Date().toISOString(),
      activeIp: '127.0.0.1',
      alertsTriageCount: 0,
      incidentsResolvedCount: 0,
      avgResponseTimeMinutes: 5.0,
      apiToken: `snt_live_${Math.random().toString(36).substring(2, 14)}`,
    };

    if (!foundUser) {
      usersDatabase.push(user as any);
    }

    currentUser = user as any;
    const token = `snt_jwt_${Buffer.from(user.email).toString('base64')}_${Date.now()}`;
    res.json({ token, user });
  });

  // POST /api/auth/register
  app.post('/api/auth/register', (req: Request, res: Response) => {
    const { name, email, role, password } = req.body;
    if (!name || !email) {
      return res.status(400).json({ message: 'Name and email are required for analyst enrollment.' });
    }

    const existing = usersDatabase.find(
      (u) => u.email.toLowerCase() === email.toLowerCase().trim()
    );
    if (existing) {
      return res.status(409).json({ message: 'Analyst email already enrolled in SentinelDesk.' });
    }

    const newUser = {
      id: `usr_soc_${Math.floor(100 + Math.random() * 900)}`,
      name: name.trim(),
      email: email.toLowerCase().trim(),
      password: password || 'SentinelSecure#2026',
      role: role || 'Tier 1 Junior Analyst',
      badge: `SD-${Math.floor(1000 + Math.random() * 9000)}`,
      department: 'SOC Operations & Triage',
      shift: 'Alpha Shift (08:00 - 16:00 UTC)',
      avatarUrl: `https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=256`,
      phoneNumber: '+1 (555) 019-9900',
      clearanceLevel: role?.includes('Lead') || role?.includes('Tier 3') ? 'TOP SECRET' : 'SECRET',
      workstation: 'SOC Ops Floor - Analyst Terminal',
      timezone: 'UTC-5 (America/New_York)',
      bio: 'Enrolled SOC security analyst.',
      mfaEnabled: false,
      mfaType: 'Disabled',
      lastLogin: new Date().toISOString(),
      activeIp: '10.0.4.55 (Local Enclave)',
      alertsTriageCount: 0,
      incidentsResolvedCount: 0,
      avgResponseTimeMinutes: 4.2,
      apiToken: `snt_live_${Math.random().toString(36).substring(2, 14)}`,
    };

    usersDatabase.push(newUser);
    currentUser = newUser;
    const token = `snt_jwt_${Buffer.from(newUser.email).toString('base64')}_${Date.now()}`;
    res.status(201).json({ token, user: newUser });
  });

  // POST /api/auth/logout
  app.post('/api/auth/logout', (_req: Request, res: Response) => {
    res.json({ success: true, message: 'Analyst logged out successfully.' });
  });

  app.get(['/api/auth/me', '/api/users/profile', '/api/auth/profile'], (_req: Request, res: Response) => {
    res.json(currentUser);
  });

  app.patch(['/api/users/profile', '/api/auth/profile'], (req: Request, res: Response) => {
    currentUser = { ...currentUser, ...req.body };
    res.json(currentUser);
  });

  app.put(['/api/users/profile', '/api/auth/profile'], (req: Request, res: Response) => {
    currentUser = { ...currentUser, ...req.body };
    res.json(currentUser);
  });

  app.post('/api/auth/change-password', (req: Request, res: Response) => {
    res.json({
      success: true,
      message: 'Password successfully rotated. Cryptographic sessions updated.',
    });
  });

  app.post('/api/auth/mfa/toggle', (req: Request, res: Response) => {
    const isEnabled = req.body.enabled ?? !currentUser.mfaEnabled;
    currentUser.mfaEnabled = isEnabled;
    currentUser.mfaType = isEnabled ? 'FIDO2 WebAuthn (YubiKey 5C NFC)' : 'Disabled';
    res.json({
      success: true,
      mfaEnabled: currentUser.mfaEnabled,
      mfaType: currentUser.mfaType,
    });
  });

  app.post('/api/auth/api-tokens', (_req: Request, res: Response) => {
    const newToken = `snt_live_${Math.random().toString(36).substring(2, 14)}_${Math.random().toString(36).substring(2, 8)}`;
    currentUser.apiToken = newToken;
    res.json({ token: newToken });
  });

  app.delete('/api/auth/api-tokens', (_req: Request, res: Response) => {
    delete (currentUser as any).apiToken;
    res.json({ success: true, message: 'Analyst API token revoked' });
  });

  // Optional periodic live telemetry generation (every 25s, realistic SIEM background ingestion)
  let backgroundFeedActive = true;
  setInterval(() => {
    if (!backgroundFeedActive || sseClients.size === 0 && wsClients.size === 0) {
      return;
    }
    // Only push if there are clients listening
    const types = ['Suspicious Login', 'Malware Indicator', 'Network Anomaly', 'Port Scan', 'Privilege Escalation'];
    const selectedType = types[Math.floor(Math.random() * types.length)];
    const randomIp = `185.${Math.floor(100 + Math.random() * 150)}.${Math.floor(10 + Math.random() * 80)}.${Math.floor(1 + Math.random() * 250)}`;
    const randomId = `ALT-${Math.floor(1030 + Math.random() * 8970)}`;

    const newAlert: SecurityAlert = {
      id: randomId,
      type: selectedType,
      title: `Automated SIEM Ingest: ${selectedType} Detected`,
      description: `Correlated behavioral anomaly identified by Sentinel Core engine from external IP ${randomIp}.`,
      severity: Math.random() > 0.65 ? 'CRITICAL' : (Math.random() > 0.4 ? 'HIGH' : 'MEDIUM'),
      status: 'OPEN',
      sourceIp: randomIp,
      destinationIp: '10.0.3.55',
      sourcePort: Math.floor(45000 + Math.random() * 15000),
      destinationPort: 443,
      protocol: 'HTTPS',
      username: 'daemon',
      hostname: 'edge-cluster-gateway',
      firstSeen: new Date().toISOString(),
      lastSeen: new Date().toISOString(),
      eventCount: Math.floor(5 + Math.random() * 120),
      investigationNotes: [],
      activityTimeline: [
        {
          id: `act-${Date.now()}`,
          action: 'Alert Ingested via Real-Time SIEM Kafka Event Stream',
          user: 'Sentinel Ingestion Engine',
          timestamp: new Date().toISOString(),
        },
      ],
      relatedEvents: [],
    };

    alertsDatabase.unshift(newAlert);
    // Keep max 50 in memory
    if (alertsDatabase.length > 50) {
      alertsDatabase.pop();
    }
    const stats = calculateStats();
    broadcastEvent('alert:created', { alert: newAlert, stats });
  }, 22000);

  // Toggle periodic background feed
  app.post('/api/alerts/stream/toggle', (req: Request, res: Response) => {
    backgroundFeedActive = req.body.active ?? !backgroundFeedActive;
    res.json({ active: backgroundFeedActive });
  });

  // --- 6. Mount Vite in Dev Mode or Static Files in Production ---
  if (process.env.NODE_ENV === 'production') {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (_req: Request, res: Response) => {
      res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
    });
  } else {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  }

  server.listen(PORT, '0.0.0.0', () => {
    console.log(`[SentinelDesk SOC] Real-time engine running at http://0.0.0.0:${PORT}`);
    console.log(`[SentinelDesk SOC] SSE stream active at /api/alerts/stream`);
    console.log(`[SentinelDesk SOC] WebSocket stream active at /ws/alerts`);
  });
}

startServer().catch((err) => {
  console.error('[SentinelDesk SOC] Fatal error during startup:', err);
  process.exit(1);
});
