import { SecurityAlert, SecurityLog, Incident, ThreatIntelligence, DashboardStats, User } from '../types';

export const INITIAL_USER: User = {
  id: 'usr_soc_09',
  name: 'Alex Vance',
  email: 'alex.vance@sentineldesk.internal',
  role: 'Tier 2 Senior SOC Analyst',
  badge: 'SD-8492',
  department: 'Cyber Threat Intelligence & Incident Response',
  shift: 'Alpha Shift (08:00 - 16:00 UTC)',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  phoneNumber: '+1 (555) 019-2834',
  clearanceLevel: 'TOP SECRET // SCI-TK',
  workstation: 'SOC Ops Floor - Pod Bravo (Console #04)',
  timezone: 'UTC-5 (America/New_York)',
  bio: 'Specialized in host intrusion forensics, living-off-the-land techniques (LotL), and threat intelligence hunting for Advanced Persistent Threats (APTs).',
  mfaEnabled: true,
  mfaType: 'FIDO2 WebAuthn (YubiKey 5C NFC)',
  lastLogin: '2026-09-24T08:00:15Z',
  activeIp: '10.0.4.18 (Encrypted WireGuard VPN)',
  alertsTriageCount: 142,
  incidentsResolvedCount: 38,
  avgResponseTimeMinutes: 3.4,
  apiToken: 'snt_live_9b4e721a94f0e2193b2a884',
};

export const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'ALT-1024',
    type: 'Brute Force',
    title: 'SSH Repeated Authentication Failures',
    description: 'Multiple failed SSH authentication attempts detected from external IP within a 60-second window.',
    severity: 'HIGH',
    status: 'OPEN',
    sourceIp: '192.168.1.20',
    destinationIp: '10.0.4.15',
    sourcePort: 54112,
    destinationPort: 22,
    protocol: 'SSH',
    username: 'admin',
    hostname: 'prod-bastion-01',
    firstSeen: '2026-09-24T10:40:12Z',
    lastSeen: '2026-09-24T10:42:11Z',
    eventCount: 47,
    assignedTo: 'Alex Vance',
    investigationNotes: [
      {
        id: 'note-1',
        author: 'Alex Vance',
        content: 'Multiple failed SSH authentication attempts detected from the same source IP within a short period. Source matches known scanning tooling.',
        timestamp: '2026-09-24T10:45:00Z',
      },
    ],
    activityTimeline: [
      {
        id: 'act-1',
        action: 'Alert Triggered by SIEM Rule #104 (SSH_BRUTEFORCE)',
        user: 'System Detector',
        timestamp: '2026-09-24T10:42:11Z',
      },
      {
        id: 'act-2',
        action: 'Assigned to Analyst Alex Vance',
        user: 'Dispatcher',
        timestamp: '2026-09-24T10:43:00Z',
      },
    ],
    relatedEvents: [
      {
        id: 'rel-1',
        timestamp: '2026-09-24T10:42:11Z',
        eventType: 'FAILED_LOGIN',
        message: 'Failed SSH authentication for root user from 192.168.1.20',
        severity: 'HIGH',
        sourceIp: '192.168.1.20',
      },
      {
        id: 'rel-2',
        timestamp: '2026-09-24T10:42:08Z',
        eventType: 'FAILED_LOGIN',
        message: 'Failed SSH authentication for admin user from 192.168.1.20',
        severity: 'HIGH',
        sourceIp: '192.168.1.20',
      },
      {
        id: 'rel-3',
        timestamp: '2026-09-24T10:41:55Z',
        eventType: 'PORT_PROBE',
        message: 'SYN connection attempt on port 22/tcp',
        severity: 'LOW',
        sourceIp: '192.168.1.20',
      },
    ],
  },
  {
    id: 'ALT-1025',
    type: 'Malware Indicator',
    title: 'Cobalt Strike Beacon Signature in Outbound HTTPS',
    description: 'Heuristic packet inspection matched Cobalt Strike malleability profile headers on egress traffic.',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    sourceIp: '10.0.12.88',
    destinationIp: '185.220.101.5',
    sourcePort: 49822,
    destinationPort: 443,
    protocol: 'HTTPS',
    username: 'svc_payroll',
    hostname: 'finance-srv-02',
    firstSeen: '2026-09-24T09:12:00Z',
    lastSeen: '2026-09-24T10:55:20Z',
    eventCount: 312,
    assignedTo: 'Alex Vance',
    investigationNotes: [
      {
        id: 'note-2',
        author: 'Alex Vance',
        content: 'Endpoint finance-srv-02 isolated via EDR API. Memory dump in progress to identify injected DLL.',
        timestamp: '2026-09-24T10:00:15Z',
      },
    ],
    activityTimeline: [
      {
        id: 'act-3',
        action: 'Critical Alert Raised by Suricata IDS',
        user: 'Network Sensor 04',
        timestamp: '2026-09-24T09:12:00Z',
      },
      {
        id: 'act-4',
        action: 'Status changed to INVESTIGATING',
        user: 'Alex Vance',
        timestamp: '2026-09-24T09:20:00Z',
      },
    ],
    relatedEvents: [
      {
        id: 'rel-4',
        timestamp: '2026-09-24T10:55:20Z',
        eventType: 'SUSPICIOUS_OUTBOUND',
        message: 'High entropy POST request payload to 185.220.101.5:443',
        severity: 'CRITICAL',
        sourceIp: '10.0.12.88',
      },
      {
        id: 'rel-5',
        timestamp: '2026-09-24T09:14:02Z',
        eventType: 'PROCESS_INJECTION',
        message: 'powershell.exe created remote thread in explorer.exe',
        severity: 'CRITICAL',
        sourceIp: '10.0.12.88',
      },
    ],
  },
  {
    id: 'ALT-1026',
    type: 'Privilege Escalation',
    title: 'Unauthorized Sudo Token Creation',
    description: 'Non-privileged local account spawned interactive root shell via sudoers CVE exploitation.',
    severity: 'HIGH',
    status: 'ESCALATED',
    sourceIp: '10.0.8.14',
    destinationIp: '10.0.8.14',
    sourcePort: 0,
    destinationPort: 0,
    protocol: 'LOCAL_IPC',
    username: 'dev_guest',
    hostname: 'k8s-worker-node-03',
    firstSeen: '2026-09-24T08:15:30Z',
    lastSeen: '2026-09-24T08:22:11Z',
    eventCount: 8,
    assignedTo: 'Sarah Connor',
    investigationNotes: [
      {
        id: 'note-3',
        author: 'Sarah Connor',
        content: 'Escalated to Tier 3 Infrastructure Sec Team. Container instance terminated.',
        timestamp: '2026-09-24T08:30:00Z',
      },
    ],
    activityTimeline: [
      {
        id: 'act-5',
        action: 'Alert generated by Auditd Daemon',
        user: 'Auditd',
        timestamp: '2026-09-24T08:15:30Z',
      },
      {
        id: 'act-6',
        action: 'Escalated to Incident INC-401',
        user: 'Sarah Connor',
        timestamp: '2026-09-24T08:45:00Z',
      },
    ],
    relatedEvents: [
      {
        id: 'rel-6',
        timestamp: '2026-09-24T08:22:11Z',
        eventType: 'PRIVILEGE_ELEVATION',
        message: 'UID 1002 executed /usr/bin/sudo with privilege flag',
        severity: 'HIGH',
        sourceIp: '10.0.8.14',
      },
    ],
  },
  {
    id: 'ALT-1027',
    type: 'Port Scan',
    title: 'Rapid TCP SYN Stealth Sweep',
    description: 'Over 1,200 ports scanned within 10 seconds across subnet 10.0.4.0/24.',
    severity: 'MEDIUM',
    status: 'OPEN',
    sourceIp: '45.155.205.233',
    destinationIp: '10.0.4.1',
    sourcePort: 60234,
    destinationPort: 80,
    protocol: 'TCP',
    username: 'unauthenticated',
    hostname: 'gw-external-edge',
    firstSeen: '2026-09-24T10:15:00Z',
    lastSeen: '2026-09-24T10:15:10Z',
    eventCount: 1240,
    investigationNotes: [],
    activityTimeline: [
      {
        id: 'act-7',
        action: 'Triggered by Edge Firewall Flow Inspector',
        user: 'Firewall-01',
        timestamp: '2026-09-24T10:15:10Z',
      },
    ],
    relatedEvents: [],
  },
  {
    id: 'ALT-1028',
    type: 'Suspicious Login',
    title: 'Impossible Travel / Anomaly Geo Login',
    description: 'User logged in from Berlin (DE) 14 minutes after active session in Austin (US).',
    severity: 'MEDIUM',
    status: 'INVESTIGATING',
    sourceIp: '194.26.29.112',
    destinationIp: '172.16.0.40',
    sourcePort: 44102,
    destinationPort: 443,
    protocol: 'HTTPS',
    username: 'm.chen',
    hostname: 'identity-sso-gateway',
    firstSeen: '2026-09-24T07:44:00Z',
    lastSeen: '2026-09-24T07:44:05Z',
    eventCount: 3,
    assignedTo: 'Alex Vance',
    investigationNotes: [
      {
        id: 'note-4',
        author: 'Alex Vance',
        content: 'Contacted user via out-of-band Slack. User confirmed they were traveling and connected to corporate VPN exit node in Frankfurt.',
        timestamp: '2026-09-24T08:10:00Z',
      },
    ],
    activityTimeline: [
      {
        id: 'act-8',
        action: 'Identity provider anomaly triggered',
        user: 'Okta Webhook',
        timestamp: '2026-09-24T07:44:05Z',
      },
    ],
    relatedEvents: [],
  },
  {
    id: 'ALT-1029',
    type: 'Suspicious Process',
    title: 'Encoded PowerShell Execution with Web Download',
    description: 'Execution of base64 encoded powershell.exe command invoking WebClient DownloadString.',
    severity: 'HIGH',
    status: 'RESOLVED',
    sourceIp: '10.0.14.50',
    destinationIp: '91.240.118.172',
    sourcePort: 51234,
    destinationPort: 8080,
    protocol: 'HTTP',
    username: 'r.stone',
    hostname: 'workstation-win11-89',
    firstSeen: '2026-09-23T16:20:00Z',
    lastSeen: '2026-09-23T16:22:15Z',
    eventCount: 14,
    assignedTo: 'Sarah Connor',
    investigationNotes: [
      {
        id: 'note-5',
        author: 'Sarah Connor',
        content: 'Authorized administrative diagnostic tool run by IT technician. Verified digital signature and ticket CHG-9411. Marked as RESOLVED.',
        timestamp: '2026-09-23T17:00:00Z',
      },
    ],
    activityTimeline: [
      {
        id: 'act-9',
        action: 'Status updated to RESOLVED',
        user: 'Sarah Connor',
        timestamp: '2026-09-23T17:00:00Z',
      },
    ],
    relatedEvents: [],
  },
  {
    id: 'ALT-1030',
    type: 'Network Anomaly',
    title: 'DNS Tunneling / High Entropy Subdomain Query Spike',
    description: 'Over 8,000 requests for random base32 subdomains under .xyz TLD detected.',
    severity: 'CRITICAL',
    status: 'OPEN',
    sourceIp: '10.0.2.77',
    destinationIp: '10.0.0.2',
    sourcePort: 53110,
    destinationPort: 53,
    protocol: 'DNS',
    username: 'svc_inventory',
    hostname: 'warehouse-db-primary',
    firstSeen: '2026-09-24T10:48:00Z',
    lastSeen: '2026-09-24T10:58:30Z',
    eventCount: 8430,
    investigationNotes: [],
    activityTimeline: [
      {
        id: 'act-10',
        action: 'Spike threshold exceeded in CoreDNS analyzer',
        user: 'DNS Sentinel Guard',
        timestamp: '2026-09-24T10:48:00Z',
      },
    ],
    relatedEvents: [],
  },
  {
    id: 'ALT-1031',
    type: 'Port Scan',
    title: 'Internal Subnet Discovery Scan',
    description: 'Internal host probing adjacent /24 network on SMB 445 and RDP 3389.',
    severity: 'LOW',
    status: 'FALSE_POSITIVE',
    sourceIp: '10.0.1.10',
    destinationIp: '10.0.1.255',
    sourcePort: 49001,
    destinationPort: 445,
    protocol: 'SMB',
    username: 'scanner_agent',
    hostname: 'tenable-nessus-scanner',
    firstSeen: '2026-09-24T06:00:00Z',
    lastSeen: '2026-09-24T06:30:00Z',
    eventCount: 450,
    assignedTo: 'Alex Vance',
    investigationNotes: [
      {
        id: 'note-6',
        author: 'Alex Vance',
        content: 'Scheduled Tenable vulnerability scan from dedicated scanner appliance. Whitelisted subnet sweep.',
        timestamp: '2026-09-24T07:00:00Z',
      },
    ],
    activityTimeline: [
      {
        id: 'act-11',
        action: 'Marked as FALSE_POSITIVE',
        user: 'Alex Vance',
        timestamp: '2026-09-24T07:00:00Z',
      },
    ],
    relatedEvents: [],
  },
];

export const INITIAL_LOGS: SecurityLog[] = [
  {
    id: 'log-101',
    timestamp: '2026-09-24 10:42:11',
    hostname: 'kali',
    username: 'admin',
    sourceIp: '192.168.1.20',
    eventType: 'FAILED_LOGIN',
    message: 'Failed SSH authentication for root user from 192.168.1.20 port 54112',
    severity: 'HIGH',
  },
  {
    id: 'log-102',
    timestamp: '2026-09-24 10:42:08',
    hostname: 'kali',
    username: 'admin',
    sourceIp: '192.168.1.20',
    eventType: 'FAILED_LOGIN',
    message: 'Failed SSH authentication for user admin (invalid password)',
    severity: 'HIGH',
  },
  {
    id: 'log-103',
    timestamp: '2026-09-24 10:41:59',
    hostname: 'kali',
    username: 'guest',
    sourceIp: '192.168.1.20',
    eventType: 'FAILED_LOGIN',
    message: 'PAM authentication failure for guest user',
    severity: 'HIGH',
  },
  {
    id: 'log-104',
    timestamp: '2026-09-24 10:40:02',
    hostname: 'finance-srv-02',
    username: 'svc_payroll',
    sourceIp: '10.0.12.88',
    eventType: 'MALWARE_C2_HEURISTIC',
    message: 'Outbound TCP connection matched Cobalt Strike beacon heartbeat pattern',
    severity: 'CRITICAL',
  },
  {
    id: 'log-105',
    timestamp: '2026-09-24 10:38:15',
    hostname: 'k8s-worker-node-03',
    username: 'dev_guest',
    sourceIp: '10.0.8.14',
    eventType: 'PRIVILEGE_ELEVATION',
    message: 'Interactive shell spawned with effective UID 0 via unauthorized sudo execute',
    severity: 'HIGH',
  },
  {
    id: 'log-106',
    timestamp: '2026-09-24 10:35:40',
    hostname: 'gw-external-edge',
    username: 'anonymous',
    sourceIp: '45.155.205.233',
    eventType: 'PORT_SCAN',
    message: 'TCP SYN scan detected: 50 target ports probed within 1500ms',
    severity: 'MEDIUM',
  },
  {
    id: 'log-107',
    timestamp: '2026-09-24 10:31:22',
    hostname: 'identity-sso-gateway',
    username: 'm.chen',
    sourceIp: '194.26.29.112',
    eventType: 'SUSPICIOUS_LOGIN',
    message: 'User authentication succeeded from novel geo-location (Frankfurt, DE)',
    severity: 'MEDIUM',
  },
  {
    id: 'log-108',
    timestamp: '2026-09-24 10:28:19',
    hostname: 'warehouse-db-primary',
    username: 'svc_inventory',
    sourceIp: '10.0.2.77',
    eventType: 'DNS_ANOMALY',
    message: 'Excessive TXT lookup queries with high entropy payload',
    severity: 'CRITICAL',
  },
  {
    id: 'log-109',
    timestamp: '2026-09-24 10:25:00',
    hostname: 'core-router-01',
    username: 'system',
    sourceIp: '10.0.0.1',
    eventType: 'CONFIG_AUDIT',
    message: 'ACL rule #841 state active: dropping incoming ICMP flood packets',
    severity: 'LOW',
  },
  {
    id: 'log-110',
    timestamp: '2026-09-24 10:20:11',
    hostname: 'tenable-nessus-scanner',
    username: 'scanner_agent',
    sourceIp: '10.0.1.10',
    eventType: 'VULN_SCAN_DISCOVERY',
    message: 'Authorized discovery probe completed on subnet 10.0.1.0/24',
    severity: 'LOW',
  },
  {
    id: 'log-111',
    timestamp: '2026-09-24 10:14:55',
    hostname: 'vpn-concentrator',
    username: 'j.doe',
    sourceIp: '72.14.201.8',
    eventType: 'VPN_SESSION_ESTABLISHED',
    message: 'MFA verified via TOTP token; session tunnel active',
    severity: 'LOW',
  },
  {
    id: 'log-112',
    timestamp: '2026-09-24 10:09:44',
    hostname: 'prod-bastion-01',
    username: 'admin',
    sourceIp: '192.168.1.20',
    eventType: 'FAILED_LOGIN',
    message: 'Exceeded maximum authentication attempts (3/3) on SSH channel',
    severity: 'HIGH',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-401',
    title: 'Finance Subnet Cobalt Strike C2 Infiltration',
    description: 'Suspicious beaconing activity originating from finance-srv-02 with remote code injection indicators.',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    assignedAnalyst: 'Alex Vance',
    assignedAnalystEmail: 'alex.vance@sentineldesk.internal',
    createdAt: '2026-09-24T09:20:00Z',
    updatedAt: '2026-09-24T10:45:00Z',
    relatedAlerts: ['ALT-1025', 'ALT-1030'],
    timeline: [
      {
        id: 'inc-act-1',
        action: 'Incident Created from Alert ALT-1025',
        user: 'Alex Vance',
        timestamp: '2026-09-24T09:20:00Z',
        details: 'Initial triage escalated to critical response protocol.',
      },
      {
        id: 'inc-act-2',
        action: 'EDR Host Network Isolation Enacted',
        user: 'Alex Vance',
        timestamp: '2026-09-24T09:35:00Z',
        details: 'Blocked outbound traffic except management bridge.',
      },
      {
        id: 'inc-act-3',
        action: 'Firewall IP Blocklist Added',
        user: 'Firewall API',
        timestamp: '2026-09-24T09:42:00Z',
        details: '185.220.101.5 added to perimeter null-route.',
      },
    ],
    investigationNotes: [
      {
        id: 'inc-note-1',
        author: 'Alex Vance',
        content: 'Malware binary identified as stage-2 loader located at C:\\Windows\\Temp\\srvmgr_upd.exe. Hash submitted to internal sandbox.',
        timestamp: '2026-09-24T09:40:00Z',
      },
      {
        id: 'inc-note-2',
        author: 'Alex Vance',
        content: 'No lateral movement observed on neighboring finance-srv-01 or SQL backend.',
        timestamp: '2026-09-24T10:30:00Z',
      },
    ],
    responseActions: [
      {
        id: 'resp-1',
        action: 'Isolate Host from Local LAN via EDR',
        status: 'EXECUTED',
        executedBy: 'Alex Vance',
        timestamp: '2026-09-24T09:35:00Z',
      },
      {
        id: 'resp-2',
        action: 'Revoke compromised svc_payroll Kerberos credentials',
        status: 'EXECUTED',
        executedBy: 'Alex Vance',
        timestamp: '2026-09-24T09:45:00Z',
      },
      {
        id: 'resp-3',
        action: 'Acquire Volatile RAM Image for Forensic Analysis',
        status: 'PENDING',
        timestamp: '2026-09-24T10:00:00Z',
      },
      {
        id: 'resp-4',
        action: 'Perform Full EDR Scrape on All Subnet 10.0.12.0/24 endpoints',
        status: 'PENDING',
        timestamp: '2026-09-24T10:15:00Z',
      },
    ],
  },
  {
    id: 'INC-402',
    title: 'SSH Distributed Brute Force Campaign against Edge Bastion',
    description: 'Coordinated credential-stuffing probe against external SSH gateways.',
    severity: 'HIGH',
    status: 'OPEN',
    assignedAnalyst: 'Sarah Connor',
    assignedAnalystEmail: 'sarah.c@sentineldesk.internal',
    createdAt: '2026-09-24T10:45:00Z',
    updatedAt: '2026-09-24T10:50:00Z',
    relatedAlerts: ['ALT-1024'],
    timeline: [
      {
        id: 'inc-act-4',
        action: 'Incident Created from Alert ALT-1024',
        user: 'Sarah Connor',
        timestamp: '2026-09-24T10:45:00Z',
        details: 'Threshold of 40 failed logins per minute exceeded.',
      },
    ],
    investigationNotes: [
      {
        id: 'inc-note-3',
        author: 'Sarah Connor',
        content: 'Fail2ban temporarily blocked IP on local bastion. Perimeter rule pending approval.',
        timestamp: '2026-09-24T10:48:00Z',
      },
    ],
    responseActions: [
      {
        id: 'resp-5',
        action: 'Perimeter BGP Null-Route 192.168.1.20',
        status: 'EXECUTED',
        executedBy: 'Sarah Connor',
        timestamp: '2026-09-24T10:49:00Z',
      },
      {
        id: 'resp-6',
        action: 'Rotate Edge Bastion Public Key Pairs',
        status: 'PENDING',
        timestamp: '2026-09-24T10:50:00Z',
      },
    ],
  },
  {
    id: 'INC-398',
    title: 'K8s Cluster Privilege Escalation via Unpatched Kernel Vulnerability',
    description: 'Container breakout attempt on production cluster node.',
    severity: 'HIGH',
    status: 'CONTAINED',
    assignedAnalyst: 'Alex Vance',
    assignedAnalystEmail: 'alex.vance@sentineldesk.internal',
    createdAt: '2026-09-24T08:30:00Z',
    updatedAt: '2026-09-24T09:15:00Z',
    relatedAlerts: ['ALT-1026'],
    timeline: [
      {
        id: 'inc-act-5',
        action: 'Node drained and cordon applied in Kubernetes cluster',
        user: 'Alex Vance',
        timestamp: '2026-09-24T08:40:00Z',
      },
    ],
    investigationNotes: [
      {
        id: 'inc-note-4',
        author: 'Alex Vance',
        content: 'Worker node isolated, image redeployed with updated kernel 6.8.0-45.',
        timestamp: '2026-09-24T09:00:00Z',
      },
    ],
    responseActions: [
      {
        id: 'resp-7',
        action: 'Cordon & Drain Node k8s-worker-node-03',
        status: 'EXECUTED',
        executedBy: 'Alex Vance',
        timestamp: '2026-09-24T08:40:00Z',
      },
    ],
  },
  {
    id: 'INC-390',
    title: 'Targeted Phishing Attachment in Logistics Team Mailboxes',
    description: 'Malicious macro document delivered to 4 mailboxes; 1 executed.',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    assignedAnalyst: 'Sarah Connor',
    assignedAnalystEmail: 'sarah.c@sentineldesk.internal',
    createdAt: '2026-09-23T14:10:00Z',
    updatedAt: '2026-09-23T18:00:00Z',
    relatedAlerts: ['ALT-1029'],
    timeline: [
      {
        id: 'inc-act-6',
        action: 'Mail messages purged globally via Microsoft Graph API',
        user: 'Sarah Connor',
        timestamp: '2026-09-23T14:40:00Z',
      },
      {
        id: 'inc-act-7',
        action: 'Endpoint restored from clean golden image',
        user: 'Sarah Connor',
        timestamp: '2026-09-23T17:30:00Z',
      },
    ],
    investigationNotes: [
      {
        id: 'inc-note-5',
        author: 'Sarah Connor',
        content: 'Post-incident review completed. Macro policy enforced at group policy tier.',
        timestamp: '2026-09-23T18:00:00Z',
      },
    ],
    responseActions: [
      {
        id: 'resp-8',
        action: 'Purge Phishing Emails from Mail Server',
        status: 'EXECUTED',
        executedBy: 'Sarah Connor',
        timestamp: '2026-09-23T14:40:00Z',
      },
    ],
  },
];

export const INITIAL_THREATS: ThreatIntelligence[] = [
  {
    ip: '192.168.1.20',
    threatType: 'Brute Force / SSH Scanner',
    riskLevel: 'HIGH',
    firstSeen: '2026-09-24 10:40:12',
    lastSeen: '2026-09-24 10:42:11',
    eventCount: 47,
    country: 'Netherlands',
    asn: 'AS49453 Global Host Network',
    reputationScore: 84,
    associatedAlertsCount: 2,
    recommendedAction: 'Null-route at edge firewall, block in perimeter ACL',
  },
  {
    ip: '185.220.101.5',
    threatType: 'Cobalt Strike C2 Server',
    riskLevel: 'CRITICAL',
    firstSeen: '2026-09-24 09:12:00',
    lastSeen: '2026-09-24 10:55:20',
    eventCount: 312,
    country: 'Germany',
    asn: 'AS200052 Tor Exit Node Group',
    reputationScore: 98,
    associatedAlertsCount: 3,
    recommendedAction: 'Immediate global egress block, isolate communicating endpoints',
  },
  {
    ip: '45.155.205.233',
    threatType: 'Mass Port Scanner / Mirai Variant',
    riskLevel: 'MEDIUM',
    firstSeen: '2026-09-24 10:15:00',
    lastSeen: '2026-09-24 10:15:10',
    eventCount: 1240,
    country: 'Seychelles',
    asn: 'AS57523 Cloud Proxies Ltd',
    reputationScore: 68,
    associatedAlertsCount: 1,
    recommendedAction: 'Drop SYN packets, rate limit incoming ICMP/TCP',
  },
  {
    ip: '194.26.29.112',
    threatType: 'Anonymizing VPN Proxy',
    riskLevel: 'MEDIUM',
    firstSeen: '2026-09-24 07:44:00',
    lastSeen: '2026-09-24 07:44:05',
    eventCount: 3,
    country: 'Czechia',
    asn: 'AS39351 Proton AG',
    reputationScore: 45,
    associatedAlertsCount: 1,
    recommendedAction: 'Enforce multi-factor authentication and device posture verification',
  },
  {
    ip: '91.240.118.172',
    threatType: 'Malware Dropper Hosting',
    riskLevel: 'HIGH',
    firstSeen: '2026-09-23 16:20:00',
    lastSeen: '2026-09-23 16:22:15',
    eventCount: 14,
    country: 'Bulgaria',
    asn: 'AS44050 Petersburg Internet Network',
    reputationScore: 91,
    associatedAlertsCount: 1,
    recommendedAction: 'Sinkhole domain in recursive DNS resolver',
  },
  {
    ip: '10.0.12.88',
    threatType: 'Compromised Internal Host (Finance)',
    riskLevel: 'CRITICAL',
    firstSeen: '2026-09-24 09:12:00',
    lastSeen: '2026-09-24 10:55:20',
    eventCount: 326,
    country: 'Internal Private Network',
    asn: 'LAN-10-VLAN-12',
    reputationScore: 95,
    associatedAlertsCount: 2,
    recommendedAction: 'Physical/VLAN quarantine, volatile memory capture',
  },
];

export const INITIAL_DASHBOARD_STATS: DashboardStats = {
  totalAlerts: 148,
  criticalAlerts: 18,
  highAlerts: 42,
  mediumAlerts: 56,
  lowAlerts: 32,
  openIncidents: 7,
  resolvedIncidents: 24,
  totalLogEvents: 148293,
  severityDistribution: {
    critical: 18,
    high: 42,
    medium: 56,
    low: 32,
  },
  alertsOverTime: [
    { timestamp: '04:00', critical: 1, high: 3, medium: 5, low: 4, total: 13 },
    { timestamp: '05:00', critical: 0, high: 4, medium: 6, low: 5, total: 15 },
    { timestamp: '06:00', critical: 2, high: 5, medium: 7, low: 3, total: 17 },
    { timestamp: '07:00', critical: 1, high: 6, medium: 9, low: 6, total: 22 },
    { timestamp: '08:00', critical: 3, high: 8, medium: 11, low: 5, total: 27 },
    { timestamp: '09:00', critical: 5, high: 10, medium: 12, low: 7, total: 34 },
    { timestamp: '10:00', critical: 6, high: 9, medium: 8, low: 4, total: 27 },
    { timestamp: '11:00', critical: 2, high: 5, medium: 6, low: 3, total: 16 },
  ],
  incidentStatusDistribution: [
    { status: 'OPEN', count: 4 },
    { status: 'INVESTIGATING', count: 3 },
    { status: 'CONTAINED', count: 2 },
    { status: 'RESOLVED', count: 24 },
  ],
  topSourceIps: [
    { ip: '192.168.1.20', events: 47, threatType: 'Brute Force / SSH', riskLevel: 'HIGH' },
    { ip: '185.220.101.5', events: 312, threatType: 'Cobalt Strike C2', riskLevel: 'CRITICAL' },
    { ip: '45.155.205.233', events: 1240, threatType: 'SYN Port Sweep', riskLevel: 'MEDIUM' },
    { ip: '10.0.12.88', events: 326, threatType: 'Internal Compromised', riskLevel: 'CRITICAL' },
    { ip: '91.240.118.172', events: 14, threatType: 'Malware Dropper', riskLevel: 'HIGH' },
  ],
  eventTypeDistribution: [
    { type: 'Brute Force', count: 42 },
    { type: 'Port Scan', count: 35 },
    { type: 'Suspicious Login', count: 28 },
    { type: 'Malware Indicator', count: 18 },
    { type: 'Privilege Escalation', count: 12 },
    { type: 'Suspicious Process', count: 8 },
    { type: 'Network Anomaly', count: 5 },
  ],
};
