import React, { useState } from 'react';
import { FileBarChart, Download, Calendar, ShieldCheck, CheckCircle2 } from 'lucide-react';

export const Reports: React.FC = () => {
  const [reportType, setReportType] = useState('daily-soc');
  const [isGenerating, setIsGenerating] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setDownloadSuccess(true);
      setTimeout(() => setDownloadSuccess(false), 3000);
    }, 1200);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-800/80 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <FileBarChart className="h-6 w-6 text-cyan-400" />
            <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-white font-mono">
              SECURITY REPORTS &amp; AUDITS
            </h1>
          </div>
          <p className="text-xs text-slate-400 mt-1 font-mono">
            Compliance telemetry, daily incident executive summaries, and threat trends
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Report configuration */}
        <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-5 shadow-lg space-y-4">
          <h3 className="text-sm font-semibold text-white uppercase font-mono">Report Settings</h3>

          <div>
            <label className="text-xs font-mono text-slate-400 block mb-1">Select Template</label>
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs font-mono text-slate-200"
            >
              <option value="daily-soc">Daily SOC Operations Summary</option>
              <option value="incident-postmortem">Critical Incidents &amp; MTTD / MTTR</option>
              <option value="soc2-compliance">SOC 2 Type II Access Audit</option>
              <option value="hostile-ips">Hostile Subnets &amp; Egress Threat Vectors</option>
            </select>
          </div>

          <div>
            <label className="text-xs font-mono text-slate-400 block mb-1">Time Range</label>
            <select className="w-full rounded-lg border border-slate-700 bg-slate-950 p-2 text-xs font-mono text-slate-200">
              <option>Last 24 Hours (Active Shift)</option>
              <option>Last 7 Days</option>
              <option>Last 30 Days (Monthly Audit)</option>
            </select>
          </div>

          <button
            onClick={handleGenerateReport}
            disabled={isGenerating}
            className="w-full flex items-center justify-center gap-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 py-2.5 px-4 text-xs font-semibold text-white transition-colors disabled:opacity-50"
          >
            <Download className="h-4 w-4" />
            {isGenerating ? 'Compiling SIEM Telemetry...' : 'Generate & Download PDF'}
          </button>

          {downloadSuccess && (
            <div className="flex items-center gap-2 rounded-lg border border-emerald-500/40 bg-emerald-500/10 p-2 text-xs text-emerald-400 font-mono">
              <CheckCircle2 className="h-4 w-4 shrink-0" />
              <span>Report compiled &amp; exported to local archive.</span>
            </div>
          )}
        </div>

        {/* Available Generated Audits */}
        <div className="md:col-span-2 rounded-xl border border-slate-800 bg-slate-900/60 p-5 shadow-lg space-y-4">
          <h3 className="text-sm font-semibold text-white uppercase font-mono">
            Recent Audit Archives
          </h3>

          <div className="divide-y divide-slate-800/60 font-mono text-xs">
            <div className="py-3 flex items-center justify-between">
              <div>
                <p className="font-semibold text-slate-200">SOC_Executive_Brief_2026-09-23.pdf</p>
                <p className="text-[11px] text-slate-500">Generated by Alex Vance • 18 Critical Alerts</p>
              </div>
              <button
                onClick={handleGenerateReport}
                className="rounded border border-slate-700 bg-slate-800/60 px-3 py-1 text-[11px] text-cyan-300 hover:bg-slate-700"
              >
                Download
              </button>
            </div>

            <div className="py-3 flex items-center justify-between">
              <div>
                <p className="font-semibold text-slate-200">Incident_INC-398_Postmortem.pdf</p>
                <p className="text-[11px] text-slate-500">Generated by Sarah Connor • K8s Breakout Remediation</p>
              </div>
              <button
                onClick={handleGenerateReport}
                className="rounded border border-slate-700 bg-slate-800/60 px-3 py-1 text-[11px] text-cyan-300 hover:bg-slate-700"
              >
                Download
              </button>
            </div>

            <div className="py-3 flex items-center justify-between">
              <div>
                <p className="font-semibold text-slate-200">Weekly_Threat_Surface_Digest_W38.pdf</p>
                <p className="text-[11px] text-slate-500">Automated SIEM Engine • 148,293 events indexed</p>
              </div>
              <button
                onClick={handleGenerateReport}
                className="rounded border border-slate-700 bg-slate-800/60 px-3 py-1 text-[11px] text-cyan-300 hover:bg-slate-700"
              >
                Download
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
